### ISSUE TITLE
Feature: Allow provide base package.json file

### ISSUE THREAD

**Issue by moshest** [lostpebble/generate-package-json-webpack-plugin#12]
It would be nice to simplify configuration by allowing the user to provide a path to base `package.json` file and inherit all configuration from this file.

For example:

```ts
new GeneratePackageJsonPlugin('./package.json', {
  includeDevDependencies: true,
  // more options...
});
```

This will allow generating files more easily and let the user to decide if we want to include the original `devDependencies` as well (default: `false`).

**Comment by lostpebble** [comment]
Totally agree. I see a lot of people already use the library in this way, so it makes complete sense. Also, nice to have the option for adding the dev dependencies directly as well - as often they're important in builds down the line, or even just executing the app itself.

As mentioned in the other issue, would be nice to eventually have the choice put directly into the single options argument - but cool to have this as a type-check for the time being on the first argument.

**Comment by lostpebble** [comment]
Just updated to 2.0.0 and simplified things, made the interface much more natural and using the installed dependencies option by default (thanks again, was a great change).

The current way to do what you'd like to achieve here, is to provide your dev dependencies directly in the base package file that's a passed into the plugin.

I've been considering allowing passing a relative path as the first argument- but I think it may confuse things, as the base package.json values should be deliberately bare - to be built upon by the plugin - if you pass a path, then it'll load the entire package.json and require users to instead deliberately exclude things somehow.

So for now, you might do something like this (to include all your `devDependencies` but generate your regular dependencies):

```js
const packageJson = JSON.parse(readFileSync(path.join(__dirname, "./package.json")).toString());
delete packageJson.dependencies;

new GeneratePackageJsonPlugin(packageJson);
```

If you can think of a better way to do it with the current 2.0.0 interface, let me know.

**Comment by moshest** [comment]
I think most people will use this line: `const packageJson = JSON.parse(readFileSync(path.join(__dirname, "./package.json")).toString());`

So I would prefer to let the library doing that by default and then handle all edge cases using flags in the options argument.


My existing code looks like this:

```ts
const packageJson = JSON.parse(fs.readFileSync('./package.json').toString());

export const packageJsonPlugin = new GeneratePackageJsonPlugin(
  {
    name: packageJson.name,
    version: packageJson.version,
    private: packageJson.private,
    scripts: {
      'start:prod': packageJson.scripts['start:prod'],
    },
  },
  './package.json',
  {
    additionalDependencies: {
      'source-map-support': packageJson.dependencies['source-map-support'],
    },
    useInstalledVersions: true,
  },
);
```

I think we can make it looks like this:

```ts
export const packageJsonPlugin = new GeneratePackageJsonPlugin({
  baseFile: './package.json',
  additionalDependencies: {
    'source-map-support': packageJson.dependencies['source-map-support'],
  },
  useInstalledVersions: true,
});
```

**Comment by lostpebble** [comment]
What you're trying to achieve in the first one can now be done quite simply though using the new API:

```tsx
const packageJson = JSON.parse(fs.readFileSync('./package.json').toString());

export const packageJsonPlugin = new GeneratePackageJsonPlugin(
  {
    name: packageJson.name,
    version: packageJson.version,
    private: packageJson.private,
    scripts: {
      'start:prod': packageJson.scripts['start:prod'],
    },
    dependencies: {
      "source-map-support": ""
    }
  },
);
```

OR

```tsx
const packageJson = JSON.parse(fs.readFileSync('./package.json').toString());

delete packageJson.dependencies;
delete packageJson.devDependencies;
packageJson.dependencies = {
  "source-map-support": ""
};

export const packageJsonPlugin = new GeneratePackageJsonPlugin(packageJson);
```

`useInstalledVersions` is defaulted to `true` now - and it will pull the correct version of any dependency that's inside the base package.json passed as the first argument. Or if you set the version directly- it will use that one.

I do like the idea of passing in a first argument that could be a string to the file as well though. Its just that it means the current way of pulling directly defined dependencies directly from the first argument (base package.json) kinda clashes with that. So maybe might have to put in some conflicting options, which could be confusing.

**Comment by lostpebble** [comment]
Going to close this for now as the current functionality (where additional dependencies are directly defined inside the first argument instead of having to provide them as an option) clashes too much with the requested functionality. Also, generally the idea is to be generating a _new_ `package.json`, so I prefer the usage of the library to be more deliberate in how the new `package.json` file is created, instead of pulling from an already used one which may have many extra dependencies which aren't useful to the final output.

If it is just about ease of use and keeping things clean, then a "source" `package.json` file with all the relevant entries could still be created on the disk and loaded into the plugin, as referenced above.
