### ISSUE TITLE
Feature: Allow adding hard coded dependencies

### ISSUE THREAD

**Issue by moshest** [lostpebble/generate-package-json-webpack-plugin#13]
Sometime there is dependencies that are not imported but required for production environment. I think we need an option to allow hard coded dependencies:

```ts
new GeneratePackageJsonPlugin({}, './package.json', {
  additionalDependencies: {
    'source-map-support': '0.5.12',
  },
  // more options...
});
```

**Comment by lostpebble** [comment]
Yep, there already is [this kind of thing](https://github.com/lostpebble/generate-package-json-webpack-plugin#adding-modules-outside-of-your-code-build-modules-etc) but it might not be completely straightforward and it has seemed to be a little on-and-off at times for me.

Being more deliberate about it like this is definitely a good move.
