### ISSUE TITLE
Peer dependencies in base package.json file

### ISSUE THREAD

**Issue by hdragos** [lostpebble/generate-package-json-webpack-plugin#20]
Greetings.

So far I have been successfully using this plugin in order to generate widgets from a given entrypoint in a bigger application with multiple dependencies. So far so good, but now that I exported the widgets, I've been dealing with a new problem: libraries such as `react` are listed in `dependencies: {}`. Let's say I want to list them as `peerDependencies: {}` in the `base.package.json` file.

My `base.package.json` file should look something like this:
```json
...
"peerDependencies" : {
        "react": "^16.13.1",
        "react-dom": "^16.8.4"
},
...
```

The problem is that after generating the new `package.json`, both `react` and `react-dom` will still appear as regular dependencies (with the version inferred from the `useInstalledVersions` flag) and as peerDependencies (with the hardcoded versions from the `base.package.json`).

I thought of implementing a mechanism that will read the hardcoded `peerDependencies` in the `base.package.json` file and add them to the output `package.json` only under the `peerDependencies` list and not under the `dependencies` list. This mechanism can be implemented under flag, such as `useHardcodedDependencies`, which can be set in the `extraOptions` object (very similar to how `useInstalledVersions` works).

**Comment by lostpebble** [comment]
Hi @hdragos ,

Okay, I can see how this is an issue. I'm not too sure about `useHardcodedDependencies` though - it sounds a little ambiguous and perhaps not very obvious as to what it might do in certain situations.

What about an option such as `ignoreDependencies: ["react", "react-dom"]` ? This will ensure that any encountering of these dependencies will just be ignored and not merged into the final `package.json` file, hence only your hard-coded `peerDependencies` will show up.

Another option would be that hard-coded dependencies always take precedence - and will automatically be ignored in the generating of the final `package.json`. If you hard-code a dependency in the `base.package.json` without a version number - then it will appear in that spot, but we will deduce the version from what's currently installed - but if you hard-code a version number as well then it'll appear in those spots with that exact version as well.

**Comment by hdragos** [comment]
I really like the `ignoreDependencies` option. It looks more versatile to me and seems to give less of a headache to users, as they won't need to ask the question: "Ok, which dependencies take precedence? The ones in `base.package.json` or the ones found by the plugin?"

Initially, I thought that the `useHardcodedDependencies` mechanism would work pretty much how you described the second option: the hardcoded dependencies would take precedence over the "discovered" ones (and this mechanism could be enabled or disabled with the help of `useHardcodedDependencies` flag). But then again, the `ignoreDependencies` seems more versatile and intuitive.

I will try to implement the `ignoreDependencies` in a new PR.

**Comment by hdragos** [comment]
@lostpebble 
After a little bit more work on this feature, I realised that there is a big problem with `ignoreDependencies`:

Let's say that you want your project to always have `react` (or any library for that matter) to be included as a `peerDependency` or `devDependency`. With the `ignoreDependencies` approach you would have something like a `base.package.json` file with all the dependencies (`normal`, `peer` and `dev`) and from that file you can easily extract what dependencies you want to ignore (so they will be added in the final bundle). The problem is: what if I want for `react` to be a peer dependency, regardless of it's version? And here is where `ignoreDependencies` fails. For a single dependency, you would need to manually change the version each time the version in your application changes. This is annoying when you have a few `peerDependencies` like these, but when you have much more dependencies in this situation, it can quickly become overwhelming.

So that being said, I went with your second option.

**Comment by lostpebble** [comment]
Thanks @hdragos , will review and merge soon. I did see some basic things which could cause issues - I'll add those as comments for now.
