### ISSUE TITLE
Webpack 5 watch loop

### ISSUE THREAD

**Issue by lorenzodallavecchia** [lostpebble/generate-package-json-webpack-plugin#23]
The plugin has some issues running in webpack 5.
When using `--watch` the plugin will continuisly cause the output package.json to be re-emitted, causing an endless loop of recompilations.

In all modes (even when not using `--watch`) webpack 5 shows these deprecation warnings:

```
(node:13032) [DEP_WEBPACK_CHUNK_MODULES_ITERABLE] DeprecationWarning: Chunk.modulesIterable: Use new ChunkGraph API
(node:13032) [DEP_WEBPACK_MODULE_ISSUER] DeprecationWarning: Module.issuer: Use new ModuleGraph API
(node:13032) [DEP_WEBPACK_COMPILATION_ASSETS] DeprecationWarning: Compilation.assets will be frozen in future, all modifications are deprecated.
BREAKING CHANGE: No more changes should happen to Compilation.assets after sealing the Compilation.
        Do changes to assets earlier, e. g. in Compilation.hooks.processAssets.
        Make sure to select an appropriate stage from Compilation.PROCESS_ASSETS_STAGE_*.
```

I suspect that the last warning about modifying `assets` is the one that causes the endless recompilation loop.

**Comment by lostpebble** [comment]
Thanks for bringing it to attention @lorenzodallavecchia .

Will have to upgrade to Webpack 5 and probably use the new ChunkGraph API- as mentioned in the deprecation warning there. Will try and take a look at this soon, otherwise PRs are always welcome!

**Comment by lorenzodallavecchia** [comment]
Thanks for the quick response @lostpebble.
I would be happy to help.

First of all I have reduced my test case since I first saw the problem in a rather complex build with sub-compilations that depend on each other output.
The issue that is causing the infinite loop is the fact that the plugin is creating a new asset source each time, which prevents webpack from recognizing that it is trying to emit the same asset and attempt to avoid such an emit. This causes a cascading loop of emissions and invalidations among the various projects.

So it looks like this should be covered by the deprecation warning about not modifying `assets`. I will try to look into that.

I wonder, what is the plan for supporting older webpack versions?
In package.json I see no `peerDependencies`, but there is a dependency on `@types/webpack@^4`, which wuold imply that version 3- are not supported. However in the code I see the old hooks instance being used alongside the new one.
Should we try to keep supporting version 4 (or even older) in the same code, or support only 5, maybe from a different branch?

**Comment by lorenzodallavecchia** [comment]
Anyway, I think it is possible to easily support webpack 5 without dropping support for the previous versions.
So there is no need for breaking changes.
I will open a PR shortly.

**Comment by lostpebble** [comment]
Thanks @lorenzodallavecchia , appreciate you looking into this! I've been a bit swamped with regular work lately...

> I wonder, what is the plan for supporting older webpack versions?

I think we should at least support Webpack 4 and 5. Since 4 has been out for a long time now. But if possible, have even more backwards compatibility- as it is now. If you can find a way to support 5 without dropping that support, it would be great!
