### ISSUE TITLE
Influx db client doesnt include in final package.json

### ISSUE THREAD

**Issue by zero88** [lostpebble/generate-package-json-webpack-plugin#29]
Hi,
Currently, I'm encountering weird issue with `@influxdata/influxdb-client` in plugin `v1.1.2` and even after upgraded to latest plugin version, still same issue

v1.1.2
`GPJWP: Ignoring module without package.json: external "@influxdata/influxdb-client"`

v2.1.0
![image](https://user-images.githubusercontent.com/10863525/101629211-94518880-3a53-11eb-9bdb-d80266b93ce2.png)

![image](https://user-images.githubusercontent.com/10863525/101628575-9bc46200-3a52-11eb-9fe6-78f311ddf34e.png)

Don't understand why it's happens because it is still having valid `package.json`. Any thought?
Thanks

**Comment by lostpebble** [comment]
Thanks for reporting. I think this may have something to do with how we're looking for the `package.json` file.

Will look into it now.

**Comment by lostpebble** [comment]
I've just tested with `@influxdata/influxdb-client` on my end- and it worked just fine.

I'm not sure why your side is not showing? Are you sure that where you are webpacking your files, that in parent node_modules folders it is able to find `@influxdata/influxdb-client` ?

**Comment by lostpebble** [comment]
... Looks like you didn't update to the latest version - so that's probably it. Please update to the latest version. `2.1.2`

**Comment by zero88** [comment]
Thank for your quick response.
Actually, this repository doesn't have tag for `2.1.2` then I thought `2.1.0` as latest tag. haha

After some test, I realize the error might come from `influxdb-client` itself or from `require.resolve`. When I tried `@influxdata/influxdb-client@1.9.0`, this plugin cannot resolve as above log. but when I using `@influxdata/influxdb-client@1.8.0`, it works well.
I already tested in local env and fresh docker image with `npm` and `yarn`

This is the different in `package.json` between 2 versions, the folder structures are same 
![image](https://user-images.githubusercontent.com/10863525/101639537-016c1a80-3a62-11eb-81f9-c9fcd5d850c5.png)

Anyway, my app works with `@influxdata/influxdb-client@1.8.0`, so just go ahead. 
However, still curious what kind of this error. haha

Thank for your feedback

**Comment by lostpebble** [comment]
> Actually, this repository doesn't have tag for 2.1.2 then I thought 2.1.0 as latest tag. haha

No, but you should always check on NPM what is the actual latest version - as sometimes, patch releases are not tagged.

> After some test, I realize the error might come from influxdb-client itself or from require.resolve. When I tried @influxdata/influxdb-client@1.9.0, this plugin cannot resolve as above log. but when I using @influxdata/influxdb-client@1.8.0, it works well.

My tests were done with `1.9.0` and it worked fine - so this must be a problem on your side. Make sure you were actually using the plugin version `2.1.2`.
