### ISSUE TITLE
EISDIR: illegal operation on a directory, read

### ISSUE THREAD

**Issue by xeroxstar** [lostpebble/generate-package-json-webpack-plugin#32]
I am getting an error `(EISDIR: illegal operation on a directory, read)`:

```
new GeneratePackageJsonPlugin(PackageJSON,{
            sourcePackageFilenames: [
                path.resolve(cwd , "./dist/"),
            ]
})
```
if I provide the path with the package.json:
```
new GeneratePackageJsonPlugin(PackageJSON,{
            sourcePackageFilenames: [
                  path.resolve(cwd , "./dist/package.json")
            ]
 })
```

i am getting this error: 
`Error: ENOENT: no such file or directory, open 'C:\Users\ts\Desktop\work\project\dist\package.json'`

once I remove the plugin everything works fine.

**Comment by xeroxstar** [comment]
I fixed it by adding  `package.json` file  in ` C:\Users\ts\Desktop\work\project\dist\` folder and once I run the webpack it works but i assumed that this plugin will generate `package.json` file automatically.

**Comment by lostpebble** [comment]
Hi @xeroxstar ,

I think you may be using the library incorrectly. The `sourcePackageFilenames` option is not the destination of the `package.json` file- at the time of building your app, `C:\Users\ts\Desktop\work\project\dist\package.json` _does not exist_ - so rightfully, the plugin cannot find it. The `sourcePackageFilenames` option is explained more in the docs- but basically its for "sourcing" version numbers from other `package.json` files (ones that are used for development and currently exist) to be placed in the final output `package.json`.

Generally, with the new version of this plugin, you can completely omit the `sourcePackageFilenames` option, as the plugin will automatically scan your `node_modules` folder for the exact installed versions of modules you are using in your code.
