### ISSUE TITLE
option for output filename

### ISSUE THREAD

**Issue by dotob** [lostpebble/generate-package-json-webpack-plugin#39]
an option to give the created package.json file a different name to not overwrite the existing packagejson would be great

**Comment by lostpebble** [comment]
It shouldn't be overwriting any existing `package.json` file- as during your Webpack build process it is placed in your build output folder (which should be immutable and created fresh each time).

In what context are you using the plugin where this is an issue?

**Comment by dotob** [comment]
@lostpebble thanks for pointing this out you're absolutely right. thats the way.
